# Generated by Django 4.2.5 on 2024-10-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applymaxim',
        ),
        migrations.AddField(
            model_name='application',
            name='applyemail',
            field=models.CharField(blank=True, max_length=30, verbose_name='email'),
        ),
    ]
