# Generated by Django 4.2.5 on 2024-11-01 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
        ('Apply', '0002_remove_application_applymaxim_application_applyemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='Groups.village'),
        ),
    ]
