# Generated by Django 4.2.5 on 2024-10-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usercomments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_numbers',
            field=models.IntegerField(default=0),
        ),
    ]
