# Generated by Django 4.2.5 on 2024-10-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usercomments', '0002_book_description_alter_book_average_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
    ]
