# Generated by Django 4.2.16 on 2024-10-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Usercomments", "0005_book_image_alter_book_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="commenter",
            field=models.CharField(default="未知用户", max_length=32, verbose_name="用户名"),
        ),
    ]
