# Generated by Django 4.2.16 on 2024-10-22 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("UserAuth", "0002_remove_user_excepting_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="简历名称")),
                ("file_path", models.CharField(max_length=200, verbose_name="简历路径")),
                (
                    "belong_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserAuth.user",
                        verbose_name="所属用户",
                    ),
                ),
            ],
        ),
    ]
