# Generated by Django 4.2.5 on 2024-11-01 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_remove_user_excepting_location_and_more'),
        ('Groups', '0001_initial'),
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gtopics', to='Groups.village')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gtopics', to='UserAuth.user')),
            ],
        ),
        migrations.CreateModel(
            name='GPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gposts', to='UserAuth.user')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gposts', to='Forum.gtopic')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='UserAuth.user')),
            ],
        ),
    ]
