# Generated by Django 4.2.5 on 2024-10-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAuth', '0002_remove_user_excepting_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villagename', models.CharField(max_length=32, verbose_name='村名')),
                ('adminemail', models.CharField(max_length=32, verbose_name='村长信箱')),
                ('maxim', models.CharField(blank=True, max_length=30, verbose_name='宣言')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_groups', to='UserAuth.user')),
                ('members', models.ManyToManyField(related_name='groups', to='UserAuth.user')),
            ],
        ),
    ]
