# Generated by Django 4.2.5 on 2024-11-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_remove_user_excepting_location_and_more'),
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.SmallIntegerField(verbose_name='经验')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_groups', to='Groups.village')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp', to='UserAuth.user')),
            ],
        ),
    ]
